### ISSUE TITLE
Minor Changes to Website

### ISSUE THREAD

**Issue by cameronjj** [QuantifiedSelfless/quantifiedSelf#31]
General (to apply to all pages):
- [ ] - Tiny logo in tab to green and gold?
- [x] - "Black Box" Theater instead of "Blackbox"
- [x] - "Theatre" when the performance and "theater" just for the black box
- [x]  Links to other sites should be yellow instead of blue?

News page:
- [x] - EEF winners post: misspelled "engineering"
- [x] - Knight winners post: "into the creation" sounds strange...
- [x] - Open Exhibit: maybe ask people to add themselves to the mailing list here, since we'll probably want to have specific hours for the open exhibition (so we can be there, running surveys)

Front page: 
- [x] - "Learn More" button doesn't go to text
- [ ] Initial text and "Learn More" button don't stay with their section when screen size changes

Tickets page:
- [x] - Change Heading to same font as the rest
- [ ] - Dates
- [x] - "we are asking that you share"
- [x] - add a period after the sentence about not taking reservations (and possibly make that sentence bold)
- [x] Add map or link to black box: http://atlas.colorado.edu/atlas-centers/center-for-media-arts-and-performance-cmap/
- [x] Add age limit to the description (18 and older?)

About Page:
- [x] - add link to EEF in first paragraph
- [x] - in overview: "Engineering" is spelled incorrectly
- [x]  Add link to the Black Box Theater
- [x]  Paul, Sam, and Michael Aaron are missing on the team list
- [x]  Should we add our advisors (e.g. Tom, Hilary, Michael...) to the Team page?  Or acknowledgements to Gary and Bret for their help.
- [ ] Add JP to the About Page

Privacy Page:
- [ ] - may look nice to reduce paragraph font
- [x] -  in overview: add comma after Tom Yeh's Sikuli Lab
- [x] - in Article 3: bullet points 4 and 5 are the same
- [x] - Article 3, bullet 6: what is "re require"
- [x] - inconsistent between "sign up" and "sign-up" -- pick one for all
- [x] - Identification: should this include the CU Fund or Knight??

**Comment by wannabeCitizen** [comment]
Did all this plus Will's comments, too!
