### ISSUE TITLE
Make promotion key and show api secured by basic authentication

### ISSUE THREAD

**Issue by peymanmortazavi** [QuantifiedSelfless/quantifiedSelf#58]

**Comment by wannabeCitizen** [comment]
May want to write up something that explains how a person authenticates. Perhaps over on slack pinning a full message that explains the admin auth process for using private endpoints.

**Comment by peymanmortazavi** [comment]
I thought I did but I'll provide more on Slack.

**Comment by mynameisfiber** [comment]
done ages ago
