### ISSUE TITLE
Check Access Tokens

### ISSUE THREAD

**Issue by mynameisfiber** [QuantifiedSelfless/quantifiedSelf#61]
@peymanmortazavi you left a todo in `user_auth.py` at https://github.com/QuantifiedSelfless/quantifiedSelf/blob/master/app/user_auth.py#L95.  I'm not exactly sure what you were imagining.

**Comment by wannabeCitizen** [comment]
Is this done @peymanmortazavi ?

**Comment by peymanmortazavi** [comment]
@mynameisfiber @wannabeCitizen it's not necessary, I was thinking of counting the access tokens and see if the ticket is non-shitty so if people hack front-end to request non-shitty tickets, we'd be able to catch it there but it doesn't really all that much. I don't think people would try to do that, and if they do, they deserve a ticket :)
